const MintData = [
  {
    id: 1,
    name: "Dragonborn",
    text: "Elegant and skillful warriors, thanks to their magic heritage and to their acute senses.",
    img: "dragonide",
    statsImg: "Mago-stats",
    textTitle: "Base form",
    int: "14",
    str: "8",
    con: "8",
    dex: "11",
    spd: "11",
    wis: "11",
  },
  {
    id: 2,
    name: "Elf",
    text: "Wise experts of the arcane, the magic heritage of dragonborns is as much evident as fearful.",
    img: "elf",
    statsImg: "Ranger-stats",
    textTitle: "Base form",
    int: "8",
    str: "8",
    con: "10",
    dex: "12",
    spd: "14",
    wis: "10",
  },
  {
    id: 3,
    name: "Dwarf",
    text: "From crude dwarfic communities rises marvelous warriors, they put in trouble the most fearful enemies.",
    img: "dwarf",
    statsImg: "Paladino-stats",
    textTitle: "Base form",
    int: "9",
    str: "12",
    con: "12",
    dex: "8",
    spd: "7",
    wis: "14",
  },
  {
    id: 4,
    name: "Human",
    text: "Humans are the most adaptable and ambitious people among the common races.",
    img: "human",
    statsImg: "Guerriero-stats",
    textTitle: "Base form",
    int: "9",
    str: "12",
    con: "11",
    dex: "10",
    spd: "10",
    wis: "10",
  },
  {
    id: 5,
    name: "Orc",
    text: "Nomad warriors, surely little tactful, destructive on battlefields.",
    img: "ogre",
    statsImg: "Barbaro-stats",
    textTitle: "Base form",
    int: "8",
    str: "11",
    con: "14",
    dex: "10",
    spd: "8",
    wis: "11",
  },
];

export default MintData;
